const players = [
  {
    name: "Simon MacDonald",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Patrick Wirth",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Bruce Takasaki",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Ross Long",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Phil Carrillo",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Don Baumgart",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Mark Dottori",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Kevin Lee",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "David Haight",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Peter Venance",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Robin Park",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Hicham Mourad",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Jean-Luc DeGagne",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "James MacDonald",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Rick Hiladie",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Bryan McCloskey",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Luke MacIsaac",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Adrian Earle",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Jason MacEwen",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Jonathan Matthews",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Steve Wilson",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Graeme Fraser",
    email: "fake_email@gmail.com",
    goalie: false,
    playing: "unconfirmed",
  },
  {
    name: "Mark Davies",
    email: "fake_email@gmail.com",
    goalie: true,
    playing: "unconfirmed",
  },
  {
    name: "Mike Steffin",
    email: "fake_email@gmail.com",
    goalie: true,
    playing: "unconfirmed",
  },
  {
    name: "Ryan Westland",
    email: "fake_email@gmail.com",
    goalie: true,
    playing: "unconfirmed",
  },
];

module.exports = players;
